/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AnalyzeProjectOptions {
  cacheDir?: string
  persistCache?: boolean
}
export interface OptimizeManifestOptions {
  inferSharedVendorChunks?: boolean
  sharedDependencyMinComponents?: number
}
export interface CacheMetrics {
  cacheEnabled: boolean
  cacheDir?: string
  totalCached: number
  invalidated: number
  filesTracked: number
  cacheHitRate: number
  lastProjectPath?: string
  analyzedComponents: number
}
export declare function analyzeProject(projectPath: string, options?: AnalyzeProjectOptions | undefined | null): Promise<unknown>
export declare function optimizeManifest(manifest: any, options?: OptimizeManifestOptions | undefined | null): Promise<unknown>
export declare function getCacheStats(): CacheMetrics
