//! APERTURE · generate `albedo/sources` type declarations from the `sources` block.
//!
//! The sibling of `forge/typegen.rs`, and the same trade: `albedo/sources` is a
//! **types-only** module with no runtime record — the transpile fold removes
//! every use, and `is_framework_runtime_import` keeps the specifier out of
//! module resolution. What ships is this `.d.ts`, written to
//! `.albedo/sources.d.ts`, which the project's `tsconfig.json` already loads
//! through its `.albedo/**/*.d.ts` include.
//!
//! ## Generated from the LOWERED registry, not the raw block
//!
//! [`emit_sources_dts`] takes a [`SourceRegistry`] — the same structure the
//! resolver, the reader and the refresh loop use — rather than the
//! `BTreeMap<String, SourceDecl>` the author wrote. That is deliberate, and it
//! is the direct lesson of the two bugs the first browser run of A1 turned up:
//! both were a second pass disagreeing with the first about what the author had
//! written. Re-scanning `{placeholder}`s here would be a second implementation
//! of `lower_path`, and the failure mode is a type that says `repo(args: {
//! owner })` about a route the resolver believes takes `{ owner, name }` —
//! green everywhere, wrong in the editor.
//!
//! There is exactly one placeholder parser, and these types are printed from
//! its output.
//!
//! ## Why `Body` defaults to `any` and not `unknown`
//!
//! `JSX.AlbedoChild` admits `string | number | boolean | null | undefined |
//! Element`, and **not** `unknown` — so an `unknown` default would make
//! `<span>{status}</span>` a type error on the very first line anyone writes
//! against a declared source, and force an annotation before the thing has been
//! seen working once.
//!
//! `any` is also the more honest type. `unknown` asserts *"this is opaque"*;
//! for a response with no declared schema the truth is *"you have not told us
//! what this is, and we cannot know"*. Narrowing costs one type argument —
//! `useSharedSlot<Repo>(github.repo({ … }))` — and when a route can declare its
//! response shape, that declared type becomes the default and the `any` goes
//! away. It is provisional, not lazy.
//!
//! ## Why the `useSharedSlot` overload is emitted HERE
//!
//! It would be more obvious to put it in the scaffold's `albedo-env.d.ts`
//! beside the FORGE one. But that file is copied into a project at `albedo
//! init` and **never updated again**, so every app scaffolded before today
//! would type-error on a feature its compiler fully supports.
//!
//! Ambient `declare module` blocks merge across files and same-name function
//! declarations become overloads, so emitting the overload into this generated
//! file reaches every project that builds — including existing ones — and it is
//! deleted together with the module it consumes when the last source goes away.
//! No dangling overload, nothing to keep in sync by hand.
//!
//! ## Determinism
//!
//! [`SourceRegistry::iter`] walks a `BTreeMap` keyed `"source.route"`, so the
//! output is byte-identical across machines and runs. This is generated output
//! that lands in a project directory; a nondeterministic one is a permanent
//! spurious diff.

use crate::aperture::declare::{PathSegment, SourceRegistry, SourceRoute};
use std::fmt::Write;
use std::time::Duration;

/// Everything above the per-source declarations. Fixed, so it is also the
/// capacity floor.
const PREAMBLE: &str = "\
// GENERATED BY ALBEDO — do not edit.
//
// Types for the external sources declared in the `sources` block of your
// albedo.config.ts. Regenerated on every build.
//
// `albedo/sources` has no runtime value: the compiler folds every read away
// while transpiling, so these declarations exist purely so your editor knows
// what you may reach for and what each route needs.

declare module \"albedo/sources\" {
  /**
   * One declared external resource, bound to its arguments.
   *
   * `__external` is a brand, not data — nothing ever constructs one of these.
   * It is what keeps `useSharedSlot` from confusing a source with a FORGE
   * collection: a collection satisfies `SharedSlotSource` and returns `Row[]`,
   * a source satisfies this and returns the body itself. An external response
   * is one value, not a list of rows.
   */
  export interface ExternalResource<Body = any> {
    readonly __external: true;
    readonly __body?: Body;
  }

";

/// Emitted after the sources, merging into the `albedo` module by declaration
/// merging. See the module docs for why it lives here.
const OVERLOAD: &str = "
declare module \"albedo\" {
  /**
   * Structural mirror of `ExternalResource` above.
   *
   * Declared structurally rather than imported, for the same reason
   * `SharedSlotSource` is: a type reference to a per-project generated module
   * would fail to resolve in a project that has not built yet.
   */
  export interface SharedSlotResource<Body = any> {
    readonly __external: true;
    readonly __body?: Body;
  }

  /**
   * Read a declared external source.
   *
   * Returns the response **body**, not an array — an external response has no
   * row identity, so it is one value. Annotate to narrow it:
   * `useSharedSlot<Repo>(github.repo({ owner: \"a\", name: \"b\" }))`.
   */
  export function useSharedSlot<Body = any>(resource: SharedSlotResource<Body>): Body;
}
";

/// The full contents of `.albedo/sources.d.ts` for `registry`.
///
/// Pure and deterministic: same registry in, same bytes out. Returns an empty
/// string for an empty registry, so the caller can treat "nothing to say" and
/// "delete the file" as the same case.
#[must_use]
pub fn emit_sources_dts(registry: &SourceRegistry) -> String {
    if registry.is_empty() {
        return String::new();
    }

    // One allocation for any realistic block. Every byte below is either
    // pushed from a `&'static str` or written in place through `fmt::Write`,
    // so there are no per-line `format!` temporaries.
    let mut out = String::with_capacity(estimated_len(registry));
    out.push_str(PREAMBLE);

    // `SourceRegistry` is a `BTreeMap` keyed `"{source}.{route}"`, and `.`
    // (0x2E) sorts below every character `require_identifier` admits — so every
    // key sharing a source prefix is contiguous, and one cursor groups them
    // without building an intermediate map. A key lexicographically between two
    // of one source's keys necessarily shares that same `"{source}."` prefix.
    let mut current: Option<&str> = None;
    for route in registry.iter() {
        let opened_here = current != Some(route.source.as_str());
        if opened_here {
            if current.is_some() {
                out.push_str("  };\n\n");
            }
            let _ = write!(
                out,
                "  /** Declared source `{}` — {} */\n  export const {}: {{\n",
                route.source,
                Comment(&route.base),
                route.source,
            );
            current = Some(route.source.as_str());
        }
        // Routes are separated by a blank line, but the first one sits directly
        // under the `{` that opened its object. Generated output still gets
        // read by people.
        write_route(&mut out, route, !opened_here);
    }
    out.push_str("  };\n}\n");
    out.push_str(OVERLOAD);
    out
}

/// Enough bytes for any realistic `sources` block, so the whole file is one
/// allocation. A low guess costs one realloc, never correctness — which is why
/// the arithmetic saturates rather than being checked.
fn estimated_len(registry: &SourceRegistry) -> usize {
    /// Preamble + `export const … {};` + one doc comment and signature.
    const PER_ROUTE: usize = 192;
    /// `name: string; ` in the signature, plus `{name}` in the doc comment.
    const PER_PARAM: usize = 24;

    PREAMBLE
        .len()
        .saturating_add(OVERLOAD.len())
        .saturating_add(registry.len().saturating_mul(PER_ROUTE))
        .saturating_add(registry.param_count().saturating_mul(PER_PARAM))
}

/// One route: a doc comment carrying what it actually requests, then the
/// method signature.
fn write_route(out: &mut String, route: &SourceRoute, separate: bool) {
    if separate {
        out.push('\n');
    }
    out.push_str("    /**\n     * `");
    out.push_str(&route.method);
    out.push(' ');
    write_template(out, route);
    out.push_str("` · refreshes every ");
    write_duration(out, route.refresh);
    out.push_str("\n     */\n    ");
    out.push_str(&route.route);

    if route.params.is_empty() {
        // No placeholder means no argument, and the empty parameter list is
        // what makes passing one a type error — matching the extractor, which
        // accepts a bare call only for a template with nothing to bind.
        out.push_str("(): ExternalResource;\n");
        return;
    }

    // Every parameter is required and every one is a `string`: the extractor
    // accepts a string literal or a route param and nothing else, and an
    // unbound placeholder yields no topic at all. `string` here is not a
    // simplification — it is the rule, stated where the author reads it.
    out.push_str("(args: {");
    for (index, param) in route.params.iter().enumerate() {
        out.push_str(if index == 0 { " " } else { "; " });
        out.push_str(param);
        out.push_str(": string");
    }
    out.push_str(" }): ExternalResource;\n");
}

/// Reconstruct the author's path template from the lowered segments, so the
/// doc comment shows `/repos/{owner}/{name}` rather than a resolved URL.
fn write_template(out: &mut String, route: &SourceRoute) {
    out.push_str(&route.base);
    for segment in &route.segments {
        match segment {
            PathSegment::Literal(text) => out.push_str(text),
            PathSegment::Param(name) => {
                out.push('{');
                out.push_str(name);
                out.push('}');
            }
        }
    }
}

/// A refresh window in the shortest exact spelling: `250ms`, `3s`, `5m`,
/// `1h30m30s`.
///
/// **Normalized, not echoed.** The input is the lowered [`Duration`], because
/// carrying the author's original string alongside it would be a second copy of
/// the same fact — and this file exists to be printed from one source of truth.
/// So `refresh: "60s"` documents as `1m`. Exact, occasionally not the spelling
/// that was typed, and only above a minute: everything shorter round-trips.
fn write_duration(out: &mut String, refresh: Duration) {
    let millis = refresh.as_millis();
    if millis == 0 {
        out.push_str("request (always revalidates)");
        return;
    }
    if millis % 1000 != 0 {
        let _ = write!(out, "{millis}ms");
        return;
    }
    // Unrolled rather than looped over `[("h", 3600), ("m", 60)]`: dividing by
    // a literal is the form that is obviously total, and two steps do not earn
    // an iterator.
    let total = refresh.as_secs();
    let mut secs = total;
    let hours = secs / 3600;
    if hours > 0 {
        let _ = write!(out, "{hours}h");
        secs = secs.saturating_sub(hours.saturating_mul(3600));
    }
    let minutes = secs / 60;
    if minutes > 0 {
        let _ = write!(out, "{minutes}m");
        secs = secs.saturating_sub(minutes.saturating_mul(60));
    }
    // A trailing `0s` is noise on `5m`, but a window under a minute IS its
    // seconds and must always print.
    if secs > 0 || total < 60 {
        let _ = write!(out, "{secs}s");
    }
}

/// Text destined for a `/** … */` block.
///
/// A `base` is a validated URL, and a validated URL may still contain `*/`
/// (`https://x.test/a*/b` parses). One of those in a comment ends it early and
/// the generated file stops compiling — a spectacular failure for a types-only
/// convenience. The check is a substring scan that allocates only on a hit, so
/// the overwhelmingly common case pays nothing.
struct Comment<'a>(&'a str);

impl std::fmt::Display for Comment<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.0.contains("*/") {
            f.write_str(&self.0.replace("*/", "*\u{200b}/"))
        } else {
            f.write_str(self.0)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::aperture::declare::{RouteDecl, SourceDecl};
    use std::collections::BTreeMap;

    fn registry(sources: &[(&str, &str, &[(&str, &str, Option<&str>)])]) -> SourceRegistry {
        let declarations: BTreeMap<String, SourceDecl> = sources
            .iter()
            .map(|(name, base, routes)| {
                (
                    (*name).to_string(),
                    SourceDecl {
                        base: (*base).to_string(),
                        auth: None,
                        headers: BTreeMap::new(),
                        routes: routes
                            .iter()
                            .map(|(route, path, refresh)| {
                                (
                                    (*route).to_string(),
                                    RouteDecl {
                                        path: (*path).to_string(),
                                        refresh: refresh.map(str::to_string),
                                        method: None,
                                    },
                                )
                            })
                            .collect(),
                    },
                )
            })
            .collect();
        SourceRegistry::from_declarations(&declarations, |_| None).expect("lowers")
    }

    fn emit(sources: &[(&str, &str, &[(&str, &str, Option<&str>)])]) -> String {
        emit_sources_dts(&registry(sources))
    }

    #[test]
    fn a_parameterised_route_requires_every_placeholder_as_a_string() {
        let dts = emit(&[(
            "github",
            "https://api.github.com",
            &[("repo", "/repos/{owner}/{name}", Some("60s"))],
        )]);
        assert!(
            dts.contains("repo(args: { owner: string; name: string }): ExternalResource;"),
            "{dts}"
        );
        assert!(
            dts.contains("`GET https://api.github.com/repos/{owner}/{name}`"),
            "the doc comment must show the template, not a resolved URL: {dts}"
        );
        // `60s` normalizes to `1m` — exact, and printed from the lowered
        // `Duration` rather than a second copy of the author's string.
        assert!(dts.contains("refreshes every 1m"), "{dts}");
    }

    /// The argument list is generated from the **lowered** `params`, in template
    /// order — the same vector the resolver mints the identity from. A second
    /// placeholder scanner here is exactly how the types would come to disagree
    /// with the compiler.
    #[test]
    fn the_argument_order_follows_the_template_not_the_declaration() {
        let dts = emit(&[("api", "https://x.test", &[("thing", "/{b}/{a}", None)])]);
        assert!(
            dts.contains("thing(args: { b: string; a: string })"),
            "{dts}"
        );
    }

    /// A bare call is legal exactly when there is nothing to bind, and the empty
    /// parameter list is what makes passing an argument a type error. Mirrors
    /// `extract_source`'s `[] => Vec::new()` arm.
    #[test]
    fn a_route_with_no_placeholders_takes_no_argument() {
        let dts = emit(&[(
            "ops",
            "https://x.test",
            &[("status", "/status", Some("3s"))],
        )]);
        assert!(dts.contains("status(): ExternalResource;"), "{dts}");
        assert!(!dts.contains("status(args"), "{dts}");
    }

    /// The registry is one flat `BTreeMap` keyed `"source.route"`; the emitter
    /// groups with a single cursor and no intermediate map. The property that
    /// makes that sound is that `.` sorts below every identifier character, so
    /// one source's keys are contiguous — including when one source name is a
    /// prefix of another.
    #[test]
    fn sources_group_even_when_one_name_prefixes_another() {
        let dts = emit(&[
            ("git", "https://a.test", &[("one", "/one", None)]),
            ("github", "https://b.test", &[("two", "/two", None)]),
            ("git0", "https://c.test", &[("three", "/three", None)]),
        ]);
        assert_eq!(dts.matches("export const git:").count(), 1, "{dts}");
        assert_eq!(dts.matches("export const git0:").count(), 1, "{dts}");
        assert_eq!(dts.matches("export const github:").count(), 1, "{dts}");
        // Three objects opened and three closed — no route orphaned into the
        // wrong source, which is the failure a broken cursor would produce.
        assert_eq!(dts.matches("export const ").count(), 3, "{dts}");
        assert_eq!(dts.matches("  };").count(), 3, "{dts}");
    }

    /// An external read is one value, not a list. The brand is what keeps the
    /// FORGE overload (`Row[]`) from claiming it.
    #[test]
    fn the_overload_returns_the_body_itself_and_is_branded() {
        let dts = emit(&[("ops", "https://x.test", &[("status", "/status", None)])]);
        assert!(
            dts.contains("export function useSharedSlot<Body = any>(resource: SharedSlotResource<Body>): Body;"),
            "{dts}"
        );
        assert!(
            dts.contains("readonly __external: true;"),
            "the brand is what disambiguates the overloads: {dts}"
        );
        assert!(
            !dts.contains("): Body[];"),
            "an external response has no row identity, so it is never an array: {dts}"
        );
    }

    /// The overload merges into `albedo` from here rather than from the
    /// scaffold, so a project generated before sources existed still gets it.
    #[test]
    fn the_module_augmentation_is_self_contained() {
        let dts = emit(&[("ops", "https://x.test", &[("status", "/status", None)])]);
        assert!(dts.contains("declare module \"albedo/sources\" {"), "{dts}");
        assert!(dts.contains("declare module \"albedo\" {"), "{dts}");
        assert!(
            !dts.contains("import "),
            "a top-level import would turn the file into a module and break \
             ambient merging — the same trap `albedo-env.d.ts` documents: {dts}"
        );
    }

    /// The caller treats "nothing to say" and "delete the file" as one case.
    #[test]
    fn an_empty_registry_emits_nothing() {
        assert!(emit_sources_dts(&SourceRegistry::default()).is_empty());
    }

    /// Shortest exact spelling, normalized from the lowered `Duration`.
    /// Everything under a minute round-trips what the author typed; above it,
    /// `60s` reads as `1m`.
    #[test]
    fn refresh_windows_print_in_their_shortest_exact_spelling() {
        let mut out = String::new();
        write_duration(&mut out, Duration::from_millis(250));
        out.push(' ');
        write_duration(&mut out, Duration::from_secs(30));
        out.push(' ');
        write_duration(&mut out, Duration::from_secs(300));
        out.push(' ');
        write_duration(&mut out, Duration::from_secs(3600));
        out.push(' ');
        write_duration(&mut out, Duration::from_secs(5430));
        out.push(' ');
        write_duration(&mut out, Duration::ZERO);
        assert_eq!(out, "250ms 30s 5m 1h 1h30m30s request (always revalidates)");
    }

    /// A validated URL may contain `*/`, and one of those inside a doc comment
    /// ends it early — turning a types-only convenience into a file that will
    /// not compile.
    #[test]
    fn a_base_containing_a_comment_terminator_cannot_break_the_file() {
        let dts = emit(&[("odd", "https://x.test/a*/b", &[("r", "/r", None)])]);
        let body = dts
            .split_once("Declared source `odd`")
            .expect("source emitted")
            .1;
        let comment_end = body.find("*/").expect("the comment must still close");
        assert!(
            !body[..comment_end].contains("*/"),
            "the base must not close the comment early: {dts}"
        );
    }

    /// Generated output that lands in a project directory. A nondeterministic
    /// one is a permanent spurious diff.
    #[test]
    fn emission_is_byte_identical_across_runs() {
        let sources: &[(&str, &str, &[(&str, &str, Option<&str>)])] = &[
            (
                "github",
                "https://api.github.com",
                &[("repo", "/repos/{owner}/{name}", Some("60s"))],
            ),
            (
                "ops",
                "https://x.test",
                &[("status", "/status", Some("3s"))],
            ),
        ];
        assert_eq!(emit(sources), emit(sources));
    }

    /// The capacity estimate should cover a realistic block in one allocation.
    /// Not a correctness property — a wrong guess only costs a realloc — but a
    /// silently useless estimate is worth catching.
    #[test]
    fn the_capacity_estimate_covers_a_realistic_block() {
        let registry = registry(&[
            (
                "github",
                "https://api.github.com",
                &[
                    ("repo", "/repos/{owner}/{name}", Some("60s")),
                    ("user", "/users/{login}", None),
                ],
            ),
            (
                "ops",
                "https://x.test",
                &[("status", "/status", Some("3s"))],
            ),
        ]);
        let estimate = estimated_len(&registry);
        assert!(
            emit_sources_dts(&registry).len() <= estimate,
            "estimate {estimate} should cover the output"
        );
    }
}
