// SPDX-License-Identifier: MIT
// bakabox `encodeActionEnvelope` writer tests.
//
// Asserts the bytes JS produces match the byte sequence bincode v2
// produces on the Rust side for the same `ActionEnvelope` values. The
// Rust-side fixture is generated by the `ir::action::round_trip*` tests
// in `src/ir/action.rs`; here we check known small encodings by hand to
// keep this self-contained (no fixture file needed for envelopes of
// this size).

import { strict as assert } from 'node:assert';
import { test } from 'node:test';

import {
  ACTION_EVENT_KIND,
  encodeActionEnvelope,
  encodeVarintU32,
  encodeVarintU64,
} from '../../assets/bincode.js';

test('encodeActionEnvelope produces the minimal 3-byte shape for empty payload', () => {
  // Matches `small_envelope_encodes_compactly` in `src/ir/action.rs`:
  // varint(1) + u8(0) + varint(0) = [1, 0, 0]
  const bytes = encodeActionEnvelope({
    actionId: 1,
    eventKind: ACTION_EVENT_KIND.Click,
    payload: new Uint8Array(0),
  });
  assert.deepStrictEqual(Array.from(bytes), [1, 0, 0]);
});

test('encodeActionEnvelope embeds the payload bytes verbatim', () => {
  const payload = new TextEncoder().encode('hi');
  const bytes = encodeActionEnvelope({
    actionId: 7,
    eventKind: ACTION_EVENT_KIND.Input,
    payload,
  });
  // [actionId=7, eventKind=1, len=2, 'h', 'i']
  assert.deepStrictEqual(Array.from(bytes), [7, 1, 2, 0x68, 0x69]);
});

test('encodeVarintU32 handles every marker boundary', () => {
  // Single-byte path: 0..=250 → one literal byte
  assert.deepStrictEqual(Array.from(encodeVarintU32(0)), [0]);
  assert.deepStrictEqual(Array.from(encodeVarintU32(250)), [250]);
  // u16 marker: 251 + 2-byte little-endian
  assert.deepStrictEqual(Array.from(encodeVarintU32(251)), [251, 251, 0]);
  assert.deepStrictEqual(Array.from(encodeVarintU32(65535)), [251, 0xff, 0xff]);
  // u32 marker: 252 + 4-byte little-endian
  assert.deepStrictEqual(
    Array.from(encodeVarintU32(65536)),
    [252, 0x00, 0x00, 0x01, 0x00],
  );
});

test('encodeVarintU64 handles BigInt inputs across marker boundaries', () => {
  assert.deepStrictEqual(Array.from(encodeVarintU64(0n)), [0]);
  assert.deepStrictEqual(Array.from(encodeVarintU64(250n)), [250]);
  assert.deepStrictEqual(Array.from(encodeVarintU64(251n)), [251, 251, 0]);
  // u64 marker at > u32::MAX
  assert.deepStrictEqual(
    Array.from(encodeVarintU64(0x1_0000_0000n)),
    [253, 0, 0, 0, 0, 1, 0, 0, 0],
  );
});

test('encodeActionEnvelope rejects bad inputs with a useful TypeError', () => {
  assert.throws(
    () => encodeActionEnvelope({ actionId: -1, eventKind: 0, payload: new Uint8Array(0) }),
    /actionId must be a non-negative integer/,
  );
  assert.throws(
    () => encodeActionEnvelope({ actionId: 0, eventKind: 999, payload: new Uint8Array(0) }),
    /eventKind must be a u8/,
  );
  assert.throws(
    () => encodeActionEnvelope({ actionId: 0, eventKind: 0, payload: 'not bytes' }),
    /payload must be a Uint8Array/,
  );
});
