//! PRISM · generate `albedo/forge` type declarations from the `forge` block.
//!
//! `import { messages } from "albedo/forge"` is a **types-only** module. It has
//! no runtime record — `transforms::shared_slots::rewrite_shared_slot_topic_args`
//! folds every use away during transpile, and `is_framework_runtime_import`
//! keeps it out of module resolution. What ships is this `.d.ts`, written to
//! `.albedo/forge.d.ts`, which the project's `tsconfig.json` already loads via
//! its `.albedo/**/*.d.ts` include (unblocked by TODO #1 item 1.5 — `.albedo`
//! used to be in `exclude`, and exclude filters include, so anything written
//! there would never have loaded).
//!
//! ## What the types buy that a runtime check cannot
//!
//! The generated `Collection<Row, PartitionCol>` types `.where` as
//! `Record<PartitionCol, string>`, and an unpartitioned collection gets
//! `never` — so `guestbook.where({ … })` is a **red squiggle in the editor**,
//! before any build runs. A misspelled collection is caught the same way,
//! because this file is the single source of which collections exist.
//!
//! ## Determinism
//!
//! Emission walks `BTreeMap`s throughout, so the file is byte-identical across
//! machines and runs. It is generated output that lands in a project directory;
//! a nondeterministic one would show up as spurious diffs forever.

use super::declare::{CollectionDecl, FieldType};
use std::collections::BTreeMap;

/// The TypeScript type a declared field lowers to.
fn ts_type(field: FieldType) -> &'static str {
    match field {
        FieldType::Text => "string",
        // Both are JS numbers. Kept as one arm with a note rather than two
        // identical ones, so a future `Bool`/`Timestamp` (item 6) has an obvious
        // place to land and the difference is visible when it does.
        FieldType::Int | FieldType::Real => "number",
    }
}

/// The full contents of `.albedo/forge.d.ts` for `declarations`.
///
/// Pure and deterministic: same declarations in, same bytes out.
#[must_use]
pub fn emit_forge_dts(declarations: &BTreeMap<String, CollectionDecl>) -> String {
    let mut out = String::new();

    out.push_str(
        "// GENERATED BY ALBEDO — do not edit.\n\
         //\n\
         // Types for the collections declared in the `forge` block of your\n\
         // albedo.config.ts. Regenerated on every build.\n\
         //\n\
         // `albedo/forge` has no runtime value: the compiler folds every read\n\
         // away while transpiling, so these declarations exist purely so your\n\
         // editor knows what your data looks like.\n\n",
    );

    // The shared shapes. `PartitionCol` is `never` for an unpartitioned
    // collection, which is what makes `.where` on one uncallable: `Record<never,
    // string>` has no satisfying argument.
    out.push_str(
        "declare module \"albedo/forge\" {\n\
         \x20 /** One partition of a collection, selected by its partition column. */\n\
         \x20 export interface Partition<Row> {\n\
         \x20   readonly __row?: Row;\n\
         \x20 }\n\n\
         \x20 /**\n\
         \x20  * A declared FORGE collection.\n\
         \x20  *\n\
         \x20  * Read the whole collection with `useSharedSlot(collection)`, or one\n\
         \x20  * partition with `useSharedSlot(collection.where({ col: params.id }))`.\n\
         \x20  * `PartitionCol` is `never` when the collection declares no\n\
         \x20  * `partition_by`, which is what makes `.where` uncallable on it.\n\
         \x20  */\n\
         \x20 export interface Collection<Row, PartitionCol extends string = never> {\n\
         \x20   readonly __row?: Row;\n\
         \x20   where(key: Record<PartitionCol, string | number>): Partition<Row>;\n\
         \x20 }\n\n",
    );

    for (name, decl) in declarations {
        let key = decl.key.clone().unwrap_or_else(|| "id".to_string());
        out.push_str(&format!("  /** Row shape of the `{name}` collection. */\n"));
        out.push_str(&format!("  export interface {} {{\n", row_type_name(name)));
        // The key column is implicit and always an INTEGER PRIMARY KEY.
        out.push_str(&format!("    {key}: number;\n"));
        for (column, ty) in &decl.fields {
            out.push_str(&format!("    {column}: {};\n", ts_type(*ty)));
        }
        out.push_str("  }\n\n");

        let partition = match &decl.partition_by {
            Some(column) => format!(", \"{column}\""),
            None => String::new(),
        };
        out.push_str(&format!(
            "  export const {name}: Collection<{}{partition}>;\n\n",
            row_type_name(name)
        ));
    }

    out.push_str("}\n");
    out
}

/// `messages` → `MessagesRow`. Deterministic and collision-free for the
/// identifier alphabet a collection name is already restricted to.
fn row_type_name(collection: &str) -> String {
    let mut out = String::with_capacity(collection.len() + 3);
    let mut capitalize = true;
    for ch in collection.chars() {
        if ch == '_' || ch == '-' {
            capitalize = true;
            continue;
        }
        if capitalize {
            out.extend(ch.to_uppercase());
            capitalize = false;
        } else {
            out.push(ch);
        }
    }
    out.push_str("Row");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn decl(fields: &[(&str, FieldType)], partition_by: Option<&str>) -> CollectionDecl {
        CollectionDecl {
            fields: fields
                .iter()
                .map(|(name, ty)| ((*name).to_string(), *ty))
                .collect(),
            partition_by: partition_by.map(str::to_string),
            ..CollectionDecl::default()
        }
    }

    fn emit(pairs: &[(&str, CollectionDecl)]) -> String {
        let map: BTreeMap<String, CollectionDecl> = pairs
            .iter()
            .map(|(name, d)| ((*name).to_string(), d.clone()))
            .collect();
        emit_forge_dts(&map)
    }

    #[test]
    fn a_row_interface_carries_the_implicit_key_and_every_declared_field() {
        let dts = emit(&[(
            "guestbook",
            decl(&[("author", FieldType::Text), ("message", FieldType::Text)], None),
        )]);
        assert!(dts.contains("export interface GuestbookRow {"), "{dts}");
        assert!(dts.contains("id: number;"), "the key is implicit: {dts}");
        assert!(dts.contains("author: string;"), "{dts}");
        assert!(dts.contains("message: string;"), "{dts}");
    }

    /// The point of the whole file: `.where` on an unpartitioned collection must
    /// be uncallable, and `Record<never, …>` is what makes it so.
    #[test]
    fn an_unpartitioned_collection_gets_never_so_where_cannot_be_called() {
        let dts = emit(&[("guestbook", decl(&[("author", FieldType::Text)], None))]);
        assert!(
            dts.contains("export const guestbook: Collection<GuestbookRow>;"),
            "no partition argument means the default `never`: {dts}"
        );
        assert!(dts.contains("PartitionCol extends string = never"), "{dts}");
    }

    #[test]
    fn a_partitioned_collection_names_its_column_as_a_literal_type() {
        let dts = emit(&[(
            "messages",
            decl(
                &[("room", FieldType::Text), ("body", FieldType::Text)],
                Some("room"),
            ),
        )]);
        assert!(
            dts.contains("export const messages: Collection<MessagesRow, \"room\">;"),
            "{dts}"
        );
    }

    #[test]
    fn int_and_real_are_both_numbers() {
        let dts = emit(&[(
            "leaderboard",
            decl(&[("score", FieldType::Int), ("ratio", FieldType::Real)], None),
        )]);
        assert!(dts.contains("score: number;"), "{dts}");
        assert!(dts.contains("ratio: number;"), "{dts}");
    }

    #[test]
    fn a_snake_case_collection_becomes_a_pascal_case_row_type() {
        assert_eq!(row_type_name("chat_messages"), "ChatMessagesRow");
        assert_eq!(row_type_name("feed"), "FeedRow");
    }

    /// Generated output that lands in a project directory. A nondeterministic
    /// one is a permanent spurious diff.
    #[test]
    fn emission_is_byte_identical_across_runs() {
        let pairs = [
            ("messages", decl(&[("room", FieldType::Text)], Some("room"))),
            ("guestbook", decl(&[("author", FieldType::Text)], None)),
        ];
        assert_eq!(emit(&pairs), emit(&pairs));
    }
}
